publisher:
  name: Italia
  description: "GitHub Italia è l'organizzazione GitHub di Developers Italia, la comunità dedicata allo sviluppo di software open-source a supporto dei servizi pubblici digitali Italiani."
  logo: assets/images/logo-italia-512x512.png
  website: https://developers.italia.it/
  short_name: IT
  tags:
    - italia
    - organizzazione
